// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSIXProject1
{
    internal sealed partial class Vsix
    {
        public const string Id = "VSIXProject1.60d9c44d-a7cf-462f-89d4-6fa9a521dba0";
        public const string Name = "VSIXProject1";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Tim Heuer";
        public const string Tags = "";
    }
}
